# RUNNING CONFIGURATION SETTING
IS_ON_PLATFORM = False
SAVE_PREPROCESSED_PAIRS = True
SAVE_SIMILARITIES = True

# TEXT PREPROCESSING SETTING
COLUMNS_TO_BE_PREPROCESSED = ['name', 'short_description', 'long_description', 'specification_text', 'all_texts']
SIMILARITIES_TO_BE_COMPUTED = ['id', 'brand', 'words', 'cos', 'descriptives', 'units']
SIMILARITIES_TO_IGNORE = ['long_description_id', 'long_description_brand', 'long_description_words',
                          'specification_text_cos', 'specification_text_descriptives',
                          'all_texts_words', 'all_texts_cos', 'all_texts_descriptives', 'all_texts_units',
                          'long_description_descriptives', 'short_description_descriptives', 'name_descriptives']
LOWER_CASE_TEXT = True
TEXT_LEMMATIZER = None

# KEYWORDS DETECTION SETTING
PERFORM_ID_DETECTION = True
PERFORM_COLOR_DETECTION = True
PERFORM_BRAND_DETECTION = False
PERFORM_UNITS_DETECTION = True

# TEXT FILTERING SETTING
MINIMAL_DETECTABLE_ID_LENGTH = 5
NUMBER_OF_TOP_DESCRIPTIVE_WORDS = 50
MAX_DESCRIPTIVE_WORD_OCCURRENCES_IN_TEXTS = 0.5
MIN_DESCRIPTIVE_WORDS_FOR_MATCH = 0
MIN_PRODUCT_NAME_SIMILARITY_FOR_MATCH = 2
MIN_MATCH_PRICE_RATIO = 0.5
MAX_MATCH_PRICE_RATIO = 2

# IMAGE PREPROCESSING SETTING
IMAGE_HASHES_SIZE = 8  # TODO: call from js somehow
IMAGE_RESIZE_WIDTH = 1024
IMAGE_RESIZE_HEIGHT = 1024
IMAGE_FILTERING = True
IMAGE_FILTERING_THRESH = 0.9
HEX_GROUPS_FOR_IMAGE_HASHES = 1

# SIMILARITY COMPUTATIONS SETTING
KEY_SIMILARITY_LIMIT = 0.9
NUMBER_SIMILARITY_DEVIATION = 0.1
STRING_SIMILARITY_DEVIATION = 0.1
UNITS_AND_VALUES_DEVIATION = 0.05
COMPUTE_TEXT_SIMILARITIES = True
COMPUTE_IMAGE_SIMILARITIES = True

# TRAINING CONFIGURATION SETTING
TEST_DATA_PROPORTION = 0.25
PRINCIPAL_COMPONENT_COUNT = 20
PERFORM_PCA_ANALYSIS = False
EQUALIZE_CLASS_IMPORTANCE = True
POSITIVE_CLASS_UPSAMPLING_RATIO = 10

# EVALUATION_CONFIGURATION SETTING
NUMBER_OF_THRESHES = 100
NUMBER_OF_THRESHES_FOR_AUC = 10
MAX_FP_RATE = 0.1
PRINT_ROC_AND_STATISTICS = True
